// <auto-generated />
using System;
using LibraryManagementSystem.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221110143456_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0811a4e-628a-4e9b-98da-9e5523f1a6d3"),
                            LibraryId = new Guid("7a6a4c0a-a8ae-452a-ab6d-2e43a2cc1ffb"),
                            Title = "Some book 1"
                        },
                        new
                        {
                            Id = new Guid("73e03a55-d760-4415-aeb5-743e9dd79f20"),
                            LibraryId = new Guid("7a6a4c0a-a8ae-452a-ab6d-2e43a2cc1ffb"),
                            Title = "Some book 2"
                        },
                        new
                        {
                            Id = new Guid("2ce20daa-4315-4a1d-b555-5a1d337de520"),
                            LibraryId = new Guid("7a6a4c0a-a8ae-452a-ab6d-2e43a2cc1ffb"),
                            Title = "Some book 3"
                        },
                        new
                        {
                            Id = new Guid("49b1ba68-e260-4a7e-9e3f-da55f79c90f4"),
                            LibraryId = new Guid("adea7009-34c0-4aa4-8284-d76757d2d5f2"),
                            Title = "Some book 4"
                        },
                        new
                        {
                            Id = new Guid("dd582fe1-1b4b-4c10-910e-e41c8b78d30c"),
                            LibraryId = new Guid("adea7009-34c0-4aa4-8284-d76757d2d5f2"),
                            Title = "Some book 5"
                        },
                        new
                        {
                            Id = new Guid("ac64849c-a923-4346-a2ad-6fa9d19cd2be"),
                            LibraryId = new Guid("adea7009-34c0-4aa4-8284-d76757d2d5f2"),
                            Title = "Other some book 1"
                        },
                        new
                        {
                            Id = new Guid("3efa03c9-c526-46ed-9808-835fd44a646e"),
                            LibraryId = new Guid("9162218a-aefd-46a4-ba6d-2bb0b02ba8ea"),
                            Title = "Other some book 2"
                        },
                        new
                        {
                            Id = new Guid("73eddf44-edc3-441f-8366-27cdf6595bc7"),
                            LibraryId = new Guid("9162218a-aefd-46a4-ba6d-2bb0b02ba8ea"),
                            Title = "Other some book 3"
                        },
                        new
                        {
                            Id = new Guid("4f47a31e-3a6b-4b61-8061-95c6619ae4f6"),
                            LibraryId = new Guid("9162218a-aefd-46a4-ba6d-2bb0b02ba8ea"),
                            Title = "Other some book 4"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Library", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("LibraryGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryGroupId");

                    b.ToTable("Libraries");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a6a4c0a-a8ae-452a-ab6d-2e43a2cc1ffb"),
                            LibraryGroupId = new Guid("e7b2e4ff-9c8a-45c4-aec5-f949d419b9c0"),
                            Name = "Library one"
                        },
                        new
                        {
                            Id = new Guid("adea7009-34c0-4aa4-8284-d76757d2d5f2"),
                            LibraryGroupId = new Guid("e7b2e4ff-9c8a-45c4-aec5-f949d419b9c0"),
                            Name = "Library two"
                        },
                        new
                        {
                            Id = new Guid("9162218a-aefd-46a4-ba6d-2bb0b02ba8ea"),
                            LibraryGroupId = new Guid("7e281174-5f21-497b-a1ff-641ac1aff60e"),
                            Name = "Library three"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.LibraryGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LibraryGroups");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7b2e4ff-9c8a-45c4-aec5-f949d419b9c0"),
                            Name = "Group 1"
                        },
                        new
                        {
                            Id = new Guid("7e281174-5f21-497b-a1ff-641ac1aff60e"),
                            Name = "Group 2"
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Page", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.ToTable("Pages");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8b177ac7-3d6e-47ca-ac5d-ef3cc6f3fa55"),
                            BookId = new Guid("f0811a4e-628a-4e9b-98da-9e5523f1a6d3"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("f7bc8168-ffdd-404a-bb3e-c78ff14c8ea7"),
                            BookId = new Guid("f0811a4e-628a-4e9b-98da-9e5523f1a6d3"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("36c60756-b7fd-4365-8d82-df6fbda877bf"),
                            BookId = new Guid("f0811a4e-628a-4e9b-98da-9e5523f1a6d3"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("5ad93bbb-6b4b-4808-b437-568243e89fc7"),
                            BookId = new Guid("73e03a55-d760-4415-aeb5-743e9dd79f20"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("9a399d4d-87bf-4e19-b957-074d6531655c"),
                            BookId = new Guid("73e03a55-d760-4415-aeb5-743e9dd79f20"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("bb1fdd84-f3b3-4b03-a3f5-db69d9609200"),
                            BookId = new Guid("73e03a55-d760-4415-aeb5-743e9dd79f20"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("bb89b97b-64ef-44ab-bb96-bd320e0e1fc8"),
                            BookId = new Guid("2ce20daa-4315-4a1d-b555-5a1d337de520"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("e1658020-57c8-48c6-8bcf-f93be5aef382"),
                            BookId = new Guid("2ce20daa-4315-4a1d-b555-5a1d337de520"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("7149f0bd-a73e-4ba8-8f49-4161489569f9"),
                            BookId = new Guid("2ce20daa-4315-4a1d-b555-5a1d337de520"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("bfa3718f-419b-46c4-9658-c2206e498f4a"),
                            BookId = new Guid("49b1ba68-e260-4a7e-9e3f-da55f79c90f4"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("6357f595-d9b3-4602-b0ac-3cdd5c95a24e"),
                            BookId = new Guid("49b1ba68-e260-4a7e-9e3f-da55f79c90f4"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("ba60ae13-cc3d-4219-94db-333e17f5071b"),
                            BookId = new Guid("49b1ba68-e260-4a7e-9e3f-da55f79c90f4"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("70a7ba0e-737f-41ea-9b52-4389108d6be9"),
                            BookId = new Guid("dd582fe1-1b4b-4c10-910e-e41c8b78d30c"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("2bd1969b-b48d-42d0-adad-f77bd7a600ac"),
                            BookId = new Guid("dd582fe1-1b4b-4c10-910e-e41c8b78d30c"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("2556a64c-1cc4-49c1-bc15-c4fb752a1f74"),
                            BookId = new Guid("dd582fe1-1b4b-4c10-910e-e41c8b78d30c"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("96541ea8-9cbe-4295-a9f4-89c4950dfcee"),
                            BookId = new Guid("ac64849c-a923-4346-a2ad-6fa9d19cd2be"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("08b6fed8-e200-41a4-a743-4451d4fd8853"),
                            BookId = new Guid("ac64849c-a923-4346-a2ad-6fa9d19cd2be"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("655f5d73-76eb-448d-96fe-34bb12872ed1"),
                            BookId = new Guid("ac64849c-a923-4346-a2ad-6fa9d19cd2be"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("03eeb89b-09e9-4886-9f41-536d8a34d142"),
                            BookId = new Guid("3efa03c9-c526-46ed-9808-835fd44a646e"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("9602c16a-41b0-4b40-bb3c-2ffd891ca7d6"),
                            BookId = new Guid("3efa03c9-c526-46ed-9808-835fd44a646e"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("28abde92-2599-4dc9-97e1-e90fd03ee878"),
                            BookId = new Guid("3efa03c9-c526-46ed-9808-835fd44a646e"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("b8a43bfc-6c1f-4749-91d3-723b41dfa21f"),
                            BookId = new Guid("73eddf44-edc3-441f-8366-27cdf6595bc7"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("6c9ecb04-e9c9-4a13-ac45-230a991e59d0"),
                            BookId = new Guid("73eddf44-edc3-441f-8366-27cdf6595bc7"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("7b506020-163a-4afc-b0fe-504c2b8ee9ef"),
                            BookId = new Guid("73eddf44-edc3-441f-8366-27cdf6595bc7"),
                            Content = "some content 3",
                            Number = 3
                        },
                        new
                        {
                            Id = new Guid("f6a4403d-1814-4807-8794-7f3ad0a8634d"),
                            BookId = new Guid("4f47a31e-3a6b-4b61-8061-95c6619ae4f6"),
                            Content = "some content 1",
                            Number = 1
                        },
                        new
                        {
                            Id = new Guid("7e15422f-1f81-4eee-ac55-7c6ad2bc4b15"),
                            BookId = new Guid("4f47a31e-3a6b-4b61-8061-95c6619ae4f6"),
                            Content = "some content 2",
                            Number = 2
                        },
                        new
                        {
                            Id = new Guid("b60db710-85c4-4451-a5b8-5cfbc7370ba8"),
                            BookId = new Guid("4f47a31e-3a6b-4b61-8061-95c6619ae4f6"),
                            Content = "some content 3",
                            Number = 3
                        });
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Book", b =>
                {
                    b.HasOne("LibraryManagementSystem.Domain.Entities.Library", "Library")
                        .WithMany("Books")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Library", b =>
                {
                    b.HasOne("LibraryManagementSystem.Domain.Entities.LibraryGroup", "LibraryGroup")
                        .WithMany("Libraries")
                        .HasForeignKey("LibraryGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibraryGroup");
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Page", b =>
                {
                    b.HasOne("LibraryManagementSystem.Domain.Entities.Book", "Book")
                        .WithMany("Pages")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Book", b =>
                {
                    b.Navigation("Pages");
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Library", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.LibraryGroup", b =>
                {
                    b.Navigation("Libraries");
                });
#pragma warning restore 612, 618
        }
    }
}
