// <auto-generated />
using System;
using LibraryManagementSystem.Infrastructure.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagementSystem.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221208165301_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("LibraryManagementSystem.Domain.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f0811a4e-628a-4e9b-98da-9e5523f1a6d3"),
                            Content = "some random content 1",
                            Title = "Some book 1"
                        },
                        new
                        {
                            Id = new Guid("73e03a55-d760-4415-aeb5-743e9dd79f20"),
                            Content = "some random content 2",
                            Title = "Some book 2"
                        },
                        new
                        {
                            Id = new Guid("2ce20daa-4315-4a1d-b555-5a1d337de520"),
                            Content = "some random content 3",
                            Title = "Some book 3"
                        },
                        new
                        {
                            Id = new Guid("49b1ba68-e260-4a7e-9e3f-da55f79c90f4"),
                            Content = "some random content 4",
                            Title = "Some book 4"
                        },
                        new
                        {
                            Id = new Guid("dd582fe1-1b4b-4c10-910e-e41c8b78d30c"),
                            Content = "some random content 5",
                            Title = "Some book 5"
                        },
                        new
                        {
                            Id = new Guid("ac64849c-a923-4346-a2ad-6fa9d19cd2be"),
                            Content = "some random content 6",
                            Title = "Other some book 1"
                        },
                        new
                        {
                            Id = new Guid("3efa03c9-c526-46ed-9808-835fd44a646e"),
                            Content = "some random content 7",
                            Title = "Other some book 2"
                        },
                        new
                        {
                            Id = new Guid("73eddf44-edc3-441f-8366-27cdf6595bc7"),
                            Content = "some random content 8",
                            Title = "Other some book 3"
                        },
                        new
                        {
                            Id = new Guid("4f47a31e-3a6b-4b61-8061-95c6619ae4f6"),
                            Content = "some random content 9",
                            Title = "Other some book 4"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
